### PR TITLE
Rename cepages artifact id

### PR DESCRIPTION
**Pull request by fpapon**

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Review by jbonofre — COMMENTED** [review]
What's the purpose (as cepages are already in their own groupId) ?

**Comment by fpapon** [comment]
> What's the purpose (as cepages are already in their own groupId) ?

The purpose is just to unified the artifact id as the other cepages have `winegrower-cepage-` prefix.
If it's not needed as they are already in their own groupId, we must remove the prefix in all cepages.

Thoughts?

**Comment by rmannibucau** [comment]
+1 to add it everywhere, groupid being ignored by 99% of packagings artifactid should contain it imho.

**Review by jbonofre — APPROVED** [review]
OK, it makes sense indeed.

**Pull request merged**
